# -*- encoding: utf-8 -*-
from . import sale_shop
from . import ir_sequence
from . import product
from . import account_tax
from . import account_account
from . import account_journal
from . import account_move_line
from . import account_invoice
from . import partner
from . import hr_job
from . import hr_employee
from . import tms
from . import tms_travel
from . import tms_fuelvoucher
from . import tms_advance
from . import tms_waybill
from . import tms_expense
from . import tms_factor
from . import tms_history
from . import tms_operation
from . import stock
from . import tms_expense_loan
from . import account_invoice_line
from . import tms_waybill_shipped_grouped
